# We currently have 3 execution environments:
# - arbiter, a linux box that does security enforcement. Should never run tests.
# - our mac machine that has 12 cores that is used to run mac tests, build mac _and_ emscripten release
# - autoscaling linux cloud that's used for everything else

steps:

# Basic Phase - Run super fast things and things that commonly catch bugs
  - label: ":mac: build-static-release.sh (master only)"
    command: '.buildkite/build-static-release.sh < /dev/null'
    # branches: master
    artifact_paths: _out_/**/*
    agents:
      os: mac
    # TODO(jez) We should only retry for specific error.
    # The one we were trying to fix was `'foo.h': file not found`
    retry:
     automatic: true

# Deploy Phase - Send the artifacts to the world
  - label: ":linux: publish.sh"
    command: '.buildkite/publish.sh'
    agents:
      os: linux
  - wait: ~

